Update patch set 1
Patch Set 1:

Wikibase\Test\Repo\Api\ApiXmlFormatTest::testSetDescriptionXmlFormat
UsageException: You do not have the permissions needed to carry out this action. (You do not have sufficient permissions)

/srv/jenkins-workspace/workspace/mediawiki-extensions-hhvm/src/includes/api/ApiBase.php:1580
/srv/jenkins-workspace/workspace/mediawiki-extensions-hhvm/src/extensions/Wikidata/extensions/Wikibase/repo/includes/Api/ApiErrorReporter.php:272
/srv/jenkins-workspace/workspace/mediawiki-extensions-hhvm/src/extensions/Wikidata/extensions/Wikibase/repo/includes/Api/ApiErrorReporter.php:252
/srv/jenkins-workspace/workspace/mediawiki-extensions-hhvm/src/extensions/Wikidata/extensions/Wikibase/repo/includes/Api/ModifyEntity.php:292
/srv/jenkins-workspace/workspace/mediawiki-extensions-hhvm/src/extensions/Wikidata/extensions/Wikibase/repo/tests/phpunit/includes/Api/ApiXmlFormatTest.php:334
/srv/jenkins-workspace/workspace/mediawiki-extensions-hhvm/src/extensions/Wikidata/extensions/Wikibase/repo/tests/phpunit/includes/Api/ApiXmlFormatTest.php:110
/srv/jenkins-workspace/workspace/mediawiki-extensions-hhvm/src/tests/phpunit/MediaWikiTestCase.php:392
/srv/jenkins-workspace/workspace/mediawiki-extensions-hhvm/src/maintenance/doMaintenance.php:111

Is that a simple syntax error or something else?

Patch-set: 1