Fix editor shortcuts not showing up
JQMIGRATE: jQuery.fn.offset() requires an element connected to a document
Uncaught TypeError: $(...).text(...).offset(...).addClass is not a function

The position of those shortcuts is off, but that seems to be caused by the
jQuery Migrate plugin.

Change-Id: If7618ef0e82c7116f7acccf272ca604d0df4e834