TtmServerException: Move to TtmServer namespace
* Exception::class under ttmserver ->Rename to TtmServerException
* Update references to TtmServerException

Bug: T335342
Change-Id: If57efc01afa0a2313f1553558495502c8b48b3d5