Load spyc.php lib on function miss, not class miss
Running the test suite dies with:

Fatal error:  Call to undefined function spyc_load() in /utils/TranslateYaml.php on line 81

It is available via a PHP fallback library, but that is only loaded when
the class Spyc is missing.  For some reason, it is present.  So instead,
load if the function is missing.

Stack trace for reference:
  1. {main}() /tests/phpunit/phpunit.php:0
  2. MediaWikiPHPUnitCommand::main() /tests/phpunit/phpunit.php:160
  3. PHPUnit_TextUI_Command->run() /tests/phpunit/MediaWikiPHPUnitCommand.php:42
  4. PHPUnit_TextUI_TestRunner->doRun() /PHPUnit/TextUI/Command.php:176
  5. PHPUnit_Framework_TestSuite->run() /PHPUnit/TextUI/TestRunner.php:349
  6. PHPUnit_Framework_TestSuite->run() /PHPUnit/Framework/TestSuite.php:705
  7. PHPUnit_Framework_TestSuite->run() /PHPUnit/Framework/TestSuite.php:705
  8. PHPUnit_Framework_TestSuite->run() /PHPUnit/Framework/TestSuite.php:705
  9. PHPUnit_Framework_TestSuite->runTest() /PHPUnit/Framework/TestSuite.php:745
 10. MediaWikiTestCase->run() /PHPUnit/Framework/TestSuite.php:775
 11. PHPUnit_Framework_TestCase->run() /tests/phpunit/MediaWikiTestCase.php:133
 12. PHPUnit_Framework_TestResult->run() /PHPUnit/Framework/TestCase.php:783
 13. PHPUnit_Framework_TestCase->runBare() /PHPUnit/Framework/TestResult.php:648
 14. PHPUnit_Framework_TestCase->runTest() /PHPUnit/Framework/TestCase.php:838
 15. ReflectionMethod->invokeArgs() /PHPUnit/Framework/TestCase.php:983
 16. MediaWikiExtensionTest->testParsing() /extensions/Translate/tests/phpunit/MediaWikiExtensionTest.php:0
 17. TranslateYaml::load() /extensions/Translate/tests/phpunit/MediaWikiExtensionTest.php:25
 18. TranslateYaml::loadString() /extensions/Translate/utils/TranslateYaml.php:132

Change-Id: I047baed841e867b155305bb97b4c1f708d595954