Update patch set 1
Topic updated from "bug" to "git-review-has-too-many-bugs".

Changing the topic to something that doesn't fail as:

Downloading refs/changes/31/96731/1 from gerrit
Cannot checkout to new branch
The following command failed with exit code 128
    "git checkout -b review/nikerabbit/bug FETCH_HEAD"
-----------------------
error: 'refs/heads/review/nikerabbit/bug/44972' exists; cannot create 'refs/heads/review/nikerabbit/bug'
fatal: Failed to lock ref for update: Not a directory

Patch-set: 1