Update patch set 5
Patch Set 5:

Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read "extension.json" file (Error code: ENOENT).
Warning: Task "test" not found. Use --force to continue.

Aborted due to warnings.

Patch-set: 5