Make Echo optional
When Echo is not loaded, the MessageGroupSubscriptionHookHandler can not
be initialized since it implements hooks provided by Echo.  The
MediaWiki structure test ServicesTest::testNoExceptions would fail to
initialize Translate:MessageGroupSubscriptionHookHandler service:

  Error: Interface "MediaWiki\Extension\Notifications\Hooks\BeforeCreateEchoEventHook"
  not found

  extensions/Translate/src/MessageGroupProcessing/MessageGroupSubscriptionHookHandler.php:19
  includes/AutoLoader.php:260
  extensions/Translate/src/ServiceWiring.php:249
  vendor/wikimedia/services/src/ServiceContainer.php:442
  vendor/wikimedia/services/src/ServiceContainer.php:406
  includes/MediaWikiServices.php:372
  vendor/wikimedia/services/src/ServiceContainer.php:414
  extensions/Translate/src/Services.php:73
  extensions/Translate/src/Services.php:178
  extensions/Translate/tests/phpunit/ServicesTest.php:26

Make MessageGroupSubscriptionHookHandler nullable and make it null when
Echo is not loaded.

Tested using:

  wfLoadExtensions( [
    'Translate',
    'UniversalLanguageSelector',
  ] );

And running the test that failed:

  ./phpunit --filter ServicesTest::testNoExceptions

Bug: T389998
Change-Id: I385903c965221664d90da7a73b2a2d54ff3f40e4
(cherry picked from commit eb5a510795d9815be4d0e2a30c980257804a2b6a)