TranslatorActivity::doQueryAndCache: Fix return type
PoolCounterWork::execute may return false. Error noticed on twn:

TypeError: MediaWiki\Extension\Translate\Statistics\TranslatorActivity::doQueryAndCache(): Return value must be of type array, bool returned

Caused by Ia018c9b306b3ec103f45bf39924bcf79ecc79c82

Change-Id: I84478dc32089137b4194fc2698b406e345de55f7