JsonFFS::isContentEqual: Allow nullable strings
To fix the following error:
TypeError: Argument 2 passed to JsonFFS::isContentEqual() must be of
the type string, null given

Caused by: Ib91f7f4cb487791a83e98b7d901641ad3e8488eb

Bug: T333820
Change-Id: Ibe758d7c571cd44faf1fbc38367000b5df60582c