In https://gerrit.wikimedia.org/r/437793 we currently get:
Error: 1283 Column 'tmf_text' cannot be part of FULLTEXT index

What causes this?

Change-Id: I115e79889aaba90e987af4b4824e91cd4a45a84d